Repository AY1920S1-CS2103T-T12-3/main, pull requests merged in 2019-10, with the labels that each got.

#79 User guide
  docs/UserGuide.adoc
  docs/images/addcommand.png
  docs/images/addevent.png
  docs/images/addperformance.png
  docs/images/aftersort.png
  docs/images/beforesort.png
  docs/images/calendar.png
  docs/images/currentui.png
  docs/images/deletecommand.png
  docs/images/editcommand.png
  docs/images/filter.png
  docs/images/find.png
  docs/images/help.png
  docs/images/select.png
  docs/stylesheets/asciidoctor.css
  docs/stylesheets/gh-pages.css
Labels: type.Task

#93 Performance command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/commands/PerformanceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PerformanceCommandParser.java
  src/main/java/seedu/address/logic/parser/PerformanceSyntax.java
  src/main/java/seedu/address/model/EventList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyEvents.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/date/AthletickDate.java
  src/main/java/seedu/address/model/performance/Event.java
  src/main/java/seedu/address/model/performance/Record.java
  src/main/java/seedu/address/model/performance/UniqueEventList.java
  src/main/java/seedu/address/model/performance/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/EventStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedRecord.java
  src/main/java/seedu/address/storage/JsonEventStorage.java
  src/main/java/seedu/address/storage/JsonSerializableEvents.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CalendarCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: type.Epic

#103 Implement display of performance on selected date
  src/main/java/seedu/address/model/performance/CalendarCompatibleRecord.java
  src/main/java/seedu/address/model/performance/Event.java
  src/main/java/seedu/address/ui/CalendarDetailPanel.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PerformanceTableContent.java
  src/main/java/seedu/address/ui/PerformanceTableHeader.java
  src/main/resources/view/CalendarDetailPanel.fxml
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/PerformanceTableContent.fxml
  src/main/resources/view/PerformanceTableHeader.fxml
Labels: priority.High
